### ISSUE TITLE
Installation instructions

### ISSUE THREAD

**Issue by Pascal666** [zdavatz/rapflag#7]
It would be nice if the readme included installation instructions.  It took me a long time to figure it out.  The below two commands are all I needed:
```
yum install ruby-devel gcc-c++ make
gem install public_suffix:2.0.5 rapflag
```

**Comment by zdavatz** [comment]
Send me a pull request for the the readme please.

**Comment by Pascal666** [comment]
#11

**Comment by zdavatz** [comment]
Thank you!
