### ISSUE TITLE
All currencies

### ISSUE THREAD

**Issue by Pascal666** [zdavatz/rapflag#8]
The documentation states:
> comment out "currencies" if you want to export all currencies.

This does not appear to be the case.  Commenting out "currencies" only pulls down BFX, BTC, ETH, USD, XMR, XRP, and ZEC.  This leaves a lot missing, such as LTC and BCH.

USD is always pulled even if it is missing from "currencies"

**Comment by zdavatz** [comment]
Yes, this is the case and needs to be fixed. Thank you for your Feedback.

**Comment by ngiger** [comment]
Added LTC and BCH to list auf default currencies. Fixed with release 1.0.7.

**Comment by zdavatz** [comment]
Closing this. Two more currencies have been added. But new currencies still have to be added via the config.yml file.
