### ISSUE TITLE
Poloniex config file options are not documented

### ISSUE THREAD

**Issue by Pascal666** [zdavatz/rapflag#9]
It would be nice if the readme listed the config file options `poloniex_api_key` and `poloniex_secret`.

**Comment by Pascal666** [comment]
Is there a separate config file option for Poloniex currencies?  I use Poloniex primarily for currencies not supported by Bitfinex.

**Comment by zdavatz** [comment]
Ok, I will send you my Poloniex file shortly.

**Comment by zdavatz** [comment]
Please also include this in your pull-request.

**Comment by Pascal666** [comment]
#11 merged

**Comment by zdavatz** [comment]
Thank you!
